### ISSUE TITLE
Kernel dead while running hw emulation example notebook

### ISSUE THREAD

**Issue by rahulj175** [Xilinx/Alveo-PYNQ#15]
Hello,

I am trying to run **_"2_hardware-emulation.ipynb"_**. Everything runs fine before "import pynq" cell. When I execute the cell , kernel becomes dead. Then I tried running it by putting the contents in a  *.py file , & it gives me the following error:

**_"terminate called after throwing an instance of 'std::runtime_error'
  what():  singleton ctor error
Aborted (core dumped)"_**

Content of *.py file
_**"
import os
os.environ['EMCONFIG_PATH'] = os.environ['PWD']
os.environ['XCL_EMULATION_MODE'] = 'hw_emu'
import pynq
"**_

I have installed all the dependencies XRT, Vitis, Dev & deployment xdma (xclbin file has been created). Can you point me as to where the issue can be.

**Comment by PeterOgden** [comment]
This is a known issue with the latest version of XRT which we're fixing in the next release of PYNQ. If you want to patch the current version the PR to fix this is at Xilinx/PYNQ#1105. Alternatively if it's possible with your application you can downgrade to the 2019.2 version of XRT (2.3.*)

**Comment by rahulj175** [comment]
Hello Peter,

Thanks for your reply. I downgraded XRT to 2019.2 & ran the example notebook of "2_hardware-emulation.ipynb" again. This time **_"import pynq"_** passed through. But while calling **_"pynq.Overlay('vadd_emu.xclbin')"_** it threw be the following error :+1: 

AttributeError                            Traceback (most recent call last)
<ipython-input-11-664c95332186> in <module>
----> 1 ol = pynq.Overlay('vadd_emu.xclbin')

~/.local/lib/python3.8/site-packages/pynq-2.5.1-py3.8-linux-x86_64.egg/pynq/overlay.py in __init__(self, bitfile_name, dtbo, download, ignore_version, device)
    453 
    454         if download:
--> 455             self.download()
    456 
    457         self.__doc__ = _build_docstring(self._ip_map._description,

~/.local/lib/python3.8/site-packages/pynq-2.5.1-py3.8-linux-x86_64.egg/pynq/overlay.py in download(self, dtbo)
    517                     Clocks.set_pl_clk(i)
    518 
--> 519         self.set_axi_port_width()
    520 
    521         super().download(self.parser)

~/.local/lib/python3.8/site-packages/pynq-2.5.1-py3.8-linux-x86_64.egg/pynq/overlay.py in set_axi_port_width(self)
    538 
    539         """
--> 540         parameter_dict = self.parser.ip_dict[self.parser.ps_name]['parameters']
    541         if self.parser.family_ps == 'zynq_ultra_ps_e':
    542             for para in ZU_FPD_SLCR_REG:

AttributeError: 'XclBin' object has no attribute 'ps_name'

**Comment by rahulj175** [comment]
Thanks Peter for the reply!! It worked after downgrading my xrt.
