### ISSUE TITLE
Wrong test_data.bin.link?

### ISSUE THREAD

**Issue by qpchen** [Xilinx/Alveo-PYNQ#17]
The "test_data.bin" url in file test_data.bin.link from `pynq_alveo_examples/notebooks/data_compression/` is actually u200 version xclbin file url.
Is there any idea of where to get the "test_data.bin" file?
Looking forward to your reply

**Comment by PeterOgden** [comment]
That is the correct test_data.bin file. The contents are irrelevant and it was a convenient size for  the demo.
