### ISSUE TITLE
PYNQ support for VCK5000

### ISSUE THREAD

**Issue by ombhilare999** [Xilinx/Alveo-PYNQ#20]
I have a vck5000 board, the specs can be found here: https://www.xilinx.com/products/boards-and-kits/vck5000.html
I had seen PYNQ supports alveo cards and resnet 50 models are being run on the card using pynq-dpu.
Can we do something similar for the vck5000 card, I could port the alveo image for the vck5000. I have all the bsp and xdc files of vck5000.
Please can you let me know if it is possible or not?

**Comment by schelleg** [comment]
Hi @ombhilare999 - no plans for adding VCK5000 support to this repository.  

I couldn't comment on what is possible as we haven't tried that platform out ourselves.  I'll close the issue now, but perhaps you'll find community members interested in the idea on https://discuss.pynq.io
